---
version: '3'

networks:
  proxy:
    name: 'proxy'
    external: true
  
  crypt:

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    networks:
      - crypt

  cryptgeon:
    image: cupcakearmy/cryptgeon:latest
    container_name: cryptgeon
    depends_on:
      - redis
    environment:
      - SIZE_LIMIT=${SIZE_LIMIT}
    restart: always
    networks:
      - crypt
      - proxy
