---
version: '3'

networks:
  proxy:
    name: 'proxy'
    external: true
  
  crypt:

services:
  redis-cryptgeon:
    image: redis:latest
    container_name: redis-cryptgeon
    restart: unless-stopped
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    networks:
      - crypt

  cryptgeon:
    image: cupcakearmy/cryptgeon:latest
    container_name: cryptgeon
    depends_on:
      - redis-cryptgeon
    environment:
      - SIZE_LIMIT=${SIZE_LIMIT}
      - REDIS=${REDIS}
    restart: unless-stopped
    networks:
      - crypt
      - proxy
